name: Poker Deploy
on:
  push:
    branches:
      - develop
    paths:
      - "examples/poker/**"
      - .github/workflows/poker.yml

defaults:
  run:
    working-directory: examples/poker

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm install ts-node -g
      - run: ts-node ../../src/cli.ts cloud deploy --appName hathora-poker --token ${{ secrets.HATHORA_TOKEN }}
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm install ts-node surge -g
      - run: COORDINATOR_HOST=coordinator.hathora.com APP_ID=38b1501a2ef61e51a3f9e34d0583aa5ee3b7bd641bc6744e723c6d704456380d ts-node ../../src/cli.ts build --only client
      - run: cp client/prototype-ui/dist/index.html client/prototype-ui/dist/200.html
      - run: surge client/prototype-ui/dist hathora-poker.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
  frontend-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm install ts-node surge -g
      - run: COORDINATOR_HOST=coordinator.hathora.com APP_ID=38b1501a2ef61e51a3f9e34d0583aa5ee3b7bd641bc6744e723c6d704456380d ts-node ../../src/cli.ts build --only client
      - run: cp client/web/dist/index.html client/web/dist/200.html
      - run: surge client/web/dist screeching-chance.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
